server.port=8080
spring.application.name=backend

spring.datasource.url=jdbc:h2:file:./data/streamflix_db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

# Comentado para que no ejecute el DROP TABLE de schema.sql siempre
#spring.sql.init.mode=always
# Mantenemos update para no perder datos en cada reinicio
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.sql.init.encoding=UTF-8
#http://localhost:8080/h2-console
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true



#spring.data.mongodb.uri=mongodb://localhost:27017/streamflix_media
spring.data.mongodb.uri=mongodb+srv://TFG-DAW-Videoclub-JSV-2026:YnFeQH6Cgk7aIb2Z@cluster0.rpmydx4.mongodb.net/streamflix_media?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=streamflix_media

#-------------------------------------------------
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


jwt.secret=UnaClaveSuperSecretaParaStreamFlixQueDebeTenerAlMenos256BitsDeLongitud!!
jwt.expiration=24