# ==========================================
# VARIABLES GLOBALES
# ==========================================
@host = http://localhost:8080/api
@contentType = application/json

# ==========================================
# 1. AUTENTICACIÓN DEL USUARIO
# ==========================================

### 1.1 Login de intento_hacker@streamflix.es
# @name loginHacker
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
  "email": "intento_hacker@streamflix.es",
  "password": "password123"
}

> {% client.global.set("tokenHacker", response.body.token); %}


# ==========================================
# 2. OPERACIONES DE ALQUILER
# ==========================================

### 2.1 Alquilar la película "Origen" (ID: 6)
# @name alquilarPeli
POST {{host}}/alquileres/6
Authorization: Bearer {{tokenHacker}}

### 2.2 Verificar que aparece en "Mis Alquileres"
# Debe devolver la película Origen en la lista
GET {{host}}/alquileres
Authorization: Bearer {{tokenHacker}}


# ==========================================
# 3. CANCELACIÓN (BORRADO LÓGICO)
# ==========================================

### 3.1 Anular el alquiler de "Origen"
# @name cancelarPeli
DELETE {{host}}/alquileres/6
Authorization: Bearer {{tokenHacker}}

### 3.2 Verificar que el catálogo de alquileres está vacío
# Debería devolver [] ya que el alquiler ha caducado lógicamente
GET {{host}}/alquileres
Authorization: Bearer {{tokenHacker}}